context: "local"

web_driver:
  chrome_binary: "/Applications/Chromium.app/Contents/MacOS/Chromium"
  firefox_binary: "/Applications/Firefox.app/Contents/MacOS/firefox-bin"

  chromium:
    cache_dir: "/tmp/chromium/cache-dir"
    data_path: "/tmp/chromium/data-path"
  firefox:
    cache_dir: "/tmp/firefox/cache-dir"
  cache:
    max_entries: 20
    max_age:
      seconds: 600


crawling:
  # Default for all bots
  parallel_factor: 1
  headers:
    user_agent: "Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0"
  max_retry_task: 0
  max_retry_proxy: 3
  data_base_path: "/tmp/htmls"
  screenshot:
    base_path: "/tmp/screenshots"
    page_ready_timeout_millis: 10000
    resolution_width: 320
    resolution_height: 192
    quality: 25
    type: "none"
  # Config for each spider
  twitter:
    data_base_path: "/tmp/htmls"
    max_retry_task: 3
    proxy: false
    webdriver: "chromium"
  instagram:
    jere_var: ${JERE_VAR}
    data_base_path: "/tmp/htmls"
    max_retry_task: 3
    proxy: false
    webdriver: "chromium"
    base_url: "https://www.instagram.com/"
    html_location:
      username_input: ".//input[@name='username']"
      password_input: ".//input[@name='password']"
      user_avatar: ".//img[@data-testid='user-avatar']"
      comment_button: ".//span[@class='_15y0l']/button"
      submit_button: ".//button[@type='submit']"
      blocked_banner: ".//div[@class='JBIyP']"
      text_area: ".//textarea[@data-testid='post-comment-text-area']"
      follow_button: ".//button[text()='Follow' or text()='Seguir']"
      unfollow_button: ".//*[@*='Following' or @*='Siguiendo' or @*='Unfollow']"
      like_button: ".//span[@class='fr66n']/button[@class='wpO6b  ']"
      like_state: ".//span[@class='fr66n']//*[name()='svg']"

api:
  name: "generic-crawler"
  port: 9291


worker:
  poll_interval: 60 # seconds


log:
  rotate:
    enabled: true
    path_file: "/tmp/logs"
    max_size: 10485760  # 1024*1024*10 = 10 MB
    backup_count: 15

  console:
    enabled: true

  level: 10 # CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10


dialect:
  enabled: true
